### ISSUE TITLE
请支持可配置上传名的功能，比如SK001这种

### ISSUE THREAD

**Issue by mwlio** [liufsd/PhotoCloud#1]
我需要预设命名
![a](https://cloud.githubusercontent.com/assets/3089831/17843151/43b7f8ae-685d-11e6-9ff0-35b982d82a1b.png)

**Comment by ohmerhe** [comment]
+1

**Comment by liufsd** [comment]
1.0版本中图片的名称就是文件的名称~可以自行重命名后上传~

**Comment by liufsd** [comment]
https://github.com/liufsd/PhotoCloud/releases/tag/v1.0 最新版本已经支持
