### ISSUE TITLE
界面文本框没对齐，不支持拖动图片文件到工具中上传

### ISSUE THREAD

**Issue by liuduoios** [liufsd/PhotoCloud#2]

**Comment by liufsd** [comment]
wow thanks.
UI细节没有做过多的调整~我只是一名学过“工业设计初级”的程序猿~
至于拖拽，个人觉得没有必要的啊。我支持你选择图片文件后command+u直接快捷键上传图片了的~ 拖拽反而显得很繁琐了的~这也是我实现这个app的初衷，极客精神~。
😄

**Comment by liuduoios** [comment]
不符合 Mac 用户的使用习惯啊

**Comment by liufsd** [comment]
拖拽这种方式，虽然挺常见的，但操作步骤比较繁琐~，作为程序猿的我们，更希望一个快捷键就能解决掉问题~
1.打开程序
2.打开拖拽面板
3.拖拽图片
4.确定按钮上传图片
vs 
1.（打开程序不需要前台）选择任意自己想要上传的图片
2.command+u(根据自己习惯设定快捷键) 直接上传图片

个人更倾向于后者快捷方式~
