### ISSUE TITLE
快捷键和上传记录中路径获取建议

### ISSUE THREAD

**Issue by Sooyung** [liufsd/PhotoCloud#4]
1、上传记录中路径获取最好是全路径，带上http://这个，另外有空格和特殊字符最好也能给个转意思，
因为markdown中的路径是不能带空格的。可以直接转好%20。
2、上传记录的界面最好也快捷弹出和刷新，每次上传之后，还要去点，自己去系统配置太麻烦了。

**Comment by liufsd** [comment]
感谢反馈，明天晚上我抽空实现一下。🙏。

**Comment by Sooyung** [comment]
太好啦。用着蛮好，平时文档都是markdown为主的。现在放入图片更方便啦。
